### ISSUE TITLE
[feat]: add custom-elements-manifest analyzer

### ISSUE THREAD

**Issue by bennypowers** [open-wc/create#48]
Steps:
1. add `@custom-elements-manifest/analyzer` as devdep to all templates
2. add `analyze` script to all templates
3. profit 

cc @thepassle

**Comment by thepassle** [comment]
Some things to think about are:

- Do we want to add the CEM to the users `.gitignore`, and then make sure the analyzer runs on prepublish?
I know some people have strong opinions on code reviews/making sure that the CEM has updated correctly, I also know people wont like seeing CEM changes in their PRs necessarily, so we'd have to make some kind of decision there.

- When do we run CEM?
Clever cloud starts the analyzer in watch mode kind of as a [side effect of the web dev server config](https://github.com/CleverCloud/clever-components/blob/master/web-dev-server.config.js#L16), so the analyzer will always run when the server runs. We could also consider creating a separate plugin to run the analyzer, maybe thats a bit 'cleaner'.

It would be nice to have the analyzer run in watch mode especially when the new version of storybook releases and makes its way into storybook-prebuilt, because then users will have up-to-date knobs/controls as they write code.

**Comment by bennypowers** [comment]
i think we shouldn't check the manifest in. imo it's a build artifact
for the dev server plugin, I think we should develop that separately, then add it here as a feat.

should that plugin live in cem repo or dev server repo cc @LarsDenBakker 
we have infra to add a plugin to cem repo, seems natural to me to put it there

**Comment by thepassle** [comment]
> i think we shouldn't check the manifest in. imo it's a build artifact

I agree. Maybe we go with that for now, we can always change it

> should that plugin live in cem repo or dev server repo cc @LarsDenBakker

I think its fine to add it to the cem repo

**Comment by bennypowers** [comment]
ok i'll start here then swing back to the build plugin if i have time
